import { Document, Page, StyleSheet, Text, View, Image } from "@react-pdf/renderer";
import moment from 'moment';

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 30,
  },
  logoContainer: {
    position: "absolute",
    top: 30,
    left: 30,
    width: 100,
    height: 100,
    marginBottom: 10,
    overflow: "hidden",
    padding: 0,
  },
  logoImage: {
    width: 100,
    height: 100,
  },
  header: {
    fontSize: 9,
    marginLeft: 120,
    marginBottom: 5,
    textAlign: "left",
  },
  headerRow: {
    flexDirection: "row",
  },
  headerText: {
    fontSize: 8,
    marginRight: 10,
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "right",
  },
  firstSeparator: {
    width: "100%",
    height: 1,
    backgroundColor: "#000000",
    marginTop: 70,
    marginBottom: 5,
  },
  table: {
    width: "100%",
    marginTop: 10,
    marginBottom: 16,
    borderStyle: "solid",
    borderColor: "#000000",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
  },
  tableRow: {
    flexDirection: "row",
    borderColor: "#000000",
  },
  tableHeader: {
    backgroundColor: "#deebf7",
    fontWeight: "bold",
  },
  tableCellNo: {
    padding: 5,
    fontSize: 7,
    flex: 1,
    textAlign: "center",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderColor: "#000000",
  },
  tableCell: {
    padding: 5,
    fontSize: 7,
    flex: 4,
    textAlign: "center",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderColor: "#000000",
  },
  summaryBox: {
    backgroundColor: "#deebf7",
    padding: 5,
    marginTop: 5,
    borderRadius: 2,
  },
  summaryText: {
    fontSize: 7,
  },
  summaryTitle: {
    fontSize: 8,
    fontWeight: "bold",
  },
  summaryField: {
    backgroundColor: "#FFFFFF",
    padding: 3,
    marginTop: 2,
    borderWidth: 1,
    borderRadius: 3,
    borderColor: "#CCCCCC",
    width: 100,
    height: 16,
  },
  summaryField2: {
    backgroundColor: "#FFFFFF",
    padding: 2,
    marginTop: 2,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: "#CCCCCC",
    width: 80,
    height: 14,
  },
  footerLine: {
    width: "100%",
    height: 1,
    backgroundColor: "#000000",
    marginTop: 5,
  },
  footerContainer: {
    position: "absolute",
    bottom: 10,
    left: 30,
    right: 30,
  },
  footerText: {
    fontSize: 7,
  },
});

const SalesReport = ({
  type,
  data,
  salesReportData,
  generatedReport,
  salesReportColumns,
}: {
  type: string;
  data?: any;
  salesReportData?: any;
  generatedReport?: any;
  salesReportColumns?: any[];
}) => {
  let image64 = data?.currentCompany?.logoLink[0]?.base64;

  // Set rowsPerPage based on report type
  const rowsPerPage = type === "Sales Collection Report" ? 14 : 20;

  // Format the date range
  const formatDateRange = () => {
    if (!salesReportData?.startDate || !salesReportData?.endDate) return "";
    
    const startDate = moment.unix(Number(salesReportData.startDate)).format('DD-MM-YYYY');
    const endDate = moment.unix(Number(salesReportData.endDate)).format('DD-MM-YYYY');
    
    return `${startDate} to ${endDate}`;
  };

  // Split data into chunks of 10 rows per page
  
  const rows = data?.rows || generatedReport || [];
  const pageCount = Math.ceil(rows.length / rowsPerPage);
  const paginatedRows = Array.from({ length: pageCount }, (_, index) =>
    rows.slice(index * rowsPerPage, (index + 1) * rowsPerPage)
  );

  // Common header content
  const renderHeader = () => (
    <>
      <View style={styles.logoContainer}>
        {image64 ? (
          <Image
            src={{ uri: image64, method: "GET", headers: { "Cache-Control": "no-cache" }, body: "" }}
            style={styles.logoImage}
          />
        ) : null}
      </View>
      <View style={styles.header}>
        <Text>{data?.currentCompany?.company ?? ""} ({data?.currentCompany?.BRN ?? ""})</Text>
        <Text style={styles.headerText}>{data?.currentCompany?.address ?? ""}</Text>
        <View style={styles.headerRow}>
          <Text style={styles.headerText}>Phone No.: {data?.currentCompany?.phoneNo ?? ""}</Text>
          <Text style={styles.headerText}>Email: {data?.currentCompany?.email ?? ""}</Text>
        </View>
      </View>
      <View>
        <View style={styles.firstSeparator} />
      </View>
      <View>
        <Text style={[styles.sectionTitle, { textAlign: "center" }]}>
          {type.toUpperCase()}
        </Text>
      </View>
      <View style={{ marginTop: 40 }}>
        <Text style={{ fontSize: 7, textAlign: "left" }}>
          Generated By: {data?.currentUser ?? ""}
        </Text>
        <Text style={{ fontSize: 7, textAlign: "left" }}>
          Date Range: {formatDateRange()}
        </Text>
      </View>
    </>
  );

  // Common table header
  const renderTableHeader = () => (
    <View style={[styles.tableRow, styles.tableHeader]}>
      {salesReportColumns?.map((column, index) => (
        <Text
          key={index}
          style={column.header === "No" ? styles.tableCellNo : styles.tableCell}
        >
          {column.header}
        </Text>
      ))}
    </View>
  );

  // Summary box content
  const renderSummaryBox = () => (
    <View style={styles.summaryBox}>
      <Text style={styles.summaryTitle}>Summary: </Text>
      <View style={{ flexDirection: "row", gap: 10 }}>
        {type === "Customer Monthly Sales Report" ? (
          <>
            <View>
              <Text style={styles.summaryText}>Total Invoices Issued:</Text>
              <View style={styles.summaryField}>
                <Text style={styles.summaryText}>{salesReportData?.total ?? ""}</Text>
              </View>
            </View>
            <View>
              <Text style={styles.summaryText}>Total Amount Invoiced:</Text>
              <View style={styles.summaryField}>
                <Text style={styles.summaryText}>{salesReportData?.totalSubtotalTaxReport ?? ""}</Text>
              </View>
            </View>
            <View>
              <Text style={styles.summaryText}>Total Paid:</Text>
              <View style={styles.summaryField}>
                <Text style={styles.summaryText}>{salesReportData?.totalPaidAmountReport ?? ""}</Text>
              </View>
            </View>
            <View>
              <Text style={styles.summaryText}>Total Outstanding:</Text>
              <View style={styles.summaryField}>
                <Text style={styles.summaryText}>{salesReportData?.totalOutstandingReport ?? ""}</Text>
              </View>
            </View>
          </>
        ) : type === "Sales Collection Report" ? (
          <>
            <View style={{ flexDirection: "row", gap: 10 }}>
              <View>
                <Text style={styles.summaryText}>Total Payments Received:</Text>
                <View style={styles.summaryField}>
                  <Text style={styles.summaryText}>{salesReportData?.totalPaidAmountReport ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>No. Of Customers Paid:</Text>
                <View style={styles.summaryField}>
                  <Text style={styles.summaryText}>{salesReportData?.total ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Average Payment Monthly:</Text>
                <View style={styles.summaryField}>
                  <Text style={styles.summaryText}>{salesReportData?.averagePaymentMonthly ?? ""}</Text>
                </View>
              </View>
            </View>
          </>
        ) : type === "Document Listing Report" ? (
          <>
            <View style={{ flexDirection: "row", gap: 6 }}>
              <View>
                <Text style={styles.summaryText}>Total No.Of Document:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.total ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Total Sales Amount:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.totalAmountReport ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Total Tax:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.totalTaxReport ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Total Discount:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.totalDiscountReport ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Total Amount After Tax:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.totalAmountAfterTaxReport ?? ""}</Text>
                </View>
              </View>
              <View>
                <Text style={styles.summaryText}>Total Amount After Discount:</Text>
                <View style={styles.summaryField2}>
                  <Text style={styles.summaryText}>{salesReportData?.totalAmountAfterDiscountReport ?? ""}</Text>
                </View>
              </View>
            </View>
          </>
        ) : (
          <>
            <Text style={styles.summaryText}>Other Information:</Text>
            <View style={styles.summaryField2}>
              <Text style={styles.summaryText}>{salesReportData?.otherInfo ?? ""}</Text>
            </View>
          </>
        )}
      </View>
    </View>
  );

  // Format decimal values to 2 decimal places
  const formatDecimal = (value: any) => {
    const num = parseFloat(value);
    return isNaN(num) ? "0.00" : num.toFixed(2);
  };

  return (
    <Document>
      {paginatedRows.map((pageRows, pageIndex) => (
        <Page
          key={pageIndex}
          size="A4"
          style={styles.page}
          render={({ pageNumber, totalPages }) => (
            <>
              {/* Render header on every page */}
              {renderHeader()}

              {/* Table */}
              <View style={styles.table}>
                {/* Table Header on every page */}
                {renderTableHeader()}
                {/* Table Rows for current page */}
                {pageRows.map((item, rowIndex) => (
                  <View style={styles.tableRow} key={item.UUID}>
                    {salesReportColumns?.map((column, colIndex) => (
                      <Text
                        key={colIndex}
                        style={column.header === "No" ? styles.tableCellNo : styles.tableCell}
                      >
                        {column.header === "No"
                          ? pageIndex * rowsPerPage + rowIndex + 1
                          : ["Invoice Amount", "Amount Paid", "Balance", "Tax", "Total", "Subtotal (Tax)", "Discount", "Subtotal (After Discount)", "Amount Received", "Paid Amount"].includes(column.header)
                            ? formatDecimal(item[column.accessorKey])
                            : item[column.accessorKey]}
                      </Text>
                    ))}
                  </View>
                ))}
              </View>

              {/* Summary Box only on the last page */}
              {pageIndex === paginatedRows.length - 1 && renderSummaryBox()}

              {/* Footer */}
              <View fixed style={styles.footerContainer}>
                <View style={styles.footerLine} />
                <View style={{ flexDirection: "row", justifyContent: "space-between", paddingTop: 5 }}>
                  <Text style={styles.footerText}>
                    {pageNumber === totalPages ? `Date Generated: ${moment().format("DD-MM-YYYY")}` : ""}
                  </Text>
                  <Text style={styles.footerText}>
                    Page {pageNumber} of {totalPages}
                  </Text>
                </View>
              </View>
            </>
          )}
        />
      ))}
    </Document>
  );
};

export default SalesReport;