import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  Image,
} from "@react-pdf/renderer";
import moment from "moment";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 30,
  },
  logoContainer: {
    position: "absolute",
    top: 30,
    left: 30,
    width: 100,
    height: 100,
    marginBottom: 10,
    overflow: "hidden",
    padding: 0,
  },
  logoImage: {
    width: 100,
    height: 100,
  },
  header: {
    fontSize: 9,
    marginLeft: 120,
    marginBottom: 5,
    textAlign: "left",
  },
  headerRow: {
    flexDirection: "row",
  },
  headerText: {
    fontSize: 8,
    marginRight: 10,
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "right",
  },
  firstSeparator: {
    width: "100%",
    height: 1,
    backgroundColor: "#000000",
    marginTop: 70,
    marginBottom: 5,
  },
  table: {
    width: "100%",
    marginTop: 10,
    marginBottom: 10,
    borderStyle: "solid",
    borderColor: "#000000",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#000000",
  },
  tableHeader: {
    backgroundColor: "#deebf7",
    borderTopWidth: 1,
    fontWeight: "bold",
  },
  tableCellNo: {
    padding: 5,
    fontSize: 7,
    flex: 1,
    textAlign: "center",
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#000000",
  },
  tableCell: {
    padding: 5,
    fontSize: 7,
    flex: 4,
    textAlign: "center",
    borderRightWidth: 1,
    borderColor: "#000000",
  },
  summaryBox: {
    backgroundColor: "#deebf7",
    padding: 10,
    marginTop: 10,
    borderRadius: 2,
  },
  summaryText: {
    fontSize: 7,
  },
  summaryTextValue: {
    fontSize: 7,
    textAlign: "right",
  },
  summaryTitle: {
    fontSize: 8,
    fontWeight: "bold",
  },
  summaryField: {
    backgroundColor: "#FFFFFF",
    padding: 3,
    marginTop: 2,
    borderWidth: 1,
    borderRadius: 3,
    borderColor: "#CCCCCC",
    width: 100,
    height: 16,
  },
  footerLine: {
    width: "100%",
    height: 1,
    backgroundColor: "#000000",
    marginTop: 5,
  },
  footerContainer: {
    position: "absolute",
    bottom: 10,
    left: 30,
    right: 30,
  },
  footerText: {
    fontSize: 7,
  },
});

const PurchaseReport = ({
  type,
  data,
  purchaseReportData,
  generatedReport,
  purchaseReportColumns,
}: {
  type: string;
  data?: any;
  purchaseReportData?: any;
  generatedReport;
  purchaseReportColumns?: any[];
}) => {
  let image64 = data?.currentCompany?.logoLink[0]?.base64;

  // Format the date range
  const formatDateRange = () => {
    if (!purchaseReportData?.startDate || !purchaseReportData?.endDate)
      return "";

    const startDate = moment
      .unix(Number(purchaseReportData.startDate))
      .format("DD-MM-YYYY");
    const endDate = moment
      .unix(Number(purchaseReportData.endDate))
      .format("DD-MM-YYYY");

    return `${startDate} to ${endDate}`;
  };

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        {/* Logo */}
        <View style={styles.logoContainer}>
          {image64 ? (
            <Image
              src={{
                uri: image64,
                method: "GET",
                headers: { "Cache-Control": "no-cache" },
                body: "",
              }}
              style={styles.logoImage}
            />
          ) : null}
        </View>

        {/* Header */}
        <View style={styles.header}>
          <Text>
            {data?.currentCompany?.company ?? ""} (
            {data?.currentCompany?.BRN ?? ""})
          </Text>
          <Text style={styles.headerText}>
            {data?.currentCompany?.address ?? ""}
          </Text>
          <View style={styles.headerRow}>
            <Text style={styles.headerText}>
              Phone No.: {data?.currentCompany?.phoneNo ?? ""}
            </Text>
            <Text style={styles.headerText}>
              Email: {data?.currentCompany?.email ?? ""}
            </Text>
          </View>
        </View>

        {/* First Separator */}
        <View>
          <View style={styles.firstSeparator} />
        </View>

        {/* Section Title */}
        <View>
          <Text style={[styles.sectionTitle, { textAlign: "center" }]}>
            {type.toUpperCase()} REPORT
          </Text>
        </View>

        {/* Generated By and Date Range */}
        <View style={{ marginTop: 40 }}>
          <Text style={{ fontSize: 7, textAlign: "left" }}>
            Generated By: {data?.currentUser ?? ""}
          </Text>
          <Text style={{ fontSize: 7, textAlign: "left" }}>
            Date Range: {formatDateRange()}
          </Text>
        </View>

        {/* Dynamic Table */}
        <View style={styles.table} wrap>
          {/* Table Header */}
          <View fixed style={[styles.tableRow, styles.tableHeader]}>
            {purchaseReportColumns?.map((column, index) => (
              <Text
                key={index}
                style={
                  column.header === "No" ? styles.tableCellNo : styles.tableCell
                }
              >
                {column.header}
              </Text>
            ))}
          </View>
          {/* Table Rows */}
          {(data?.rows || generatedReport)?.map((item, rowIndex) => (
            <View style={styles.tableRow} wrap={false} key={item.UUID}>
              {purchaseReportColumns?.map((column, colIndex) => (
                <Text
                  key={colIndex}
                  style={
                    column.header === "No"
                      ? styles.tableCellNo
                      : styles.tableCell
                  }
                >
                  {column.header === "No"
                    ? rowIndex + 1
                    : item[column.accessorKey]}
                </Text>
              ))}
            </View>
          ))}
        </View>

        {/* Summary Box */}
        <View style={styles.summaryBox}>
          <Text style={styles.summaryTitle}>Summary: </Text>
          <View style={{ marginTop: 5 }}>
            {type === "Supplier Monthly Purchase" ? (
              <>
                <View style={{ flexDirection: "row", gap: 10 }}>
                  <View>
                    <Text style={styles.summaryText}>
                      Total Purchase Amount:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalPurchaseAmount}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Total Paid to Supplier:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalPaidToSuppliers}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Outstanding Payables:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.outstandingPayables}
                      </Text>
                    </View>
                  </View>
                </View>
              </>
            ) : type === "Supplier Payment" ? (
              <>
                <View style={{ flexDirection: "row", gap: 10 }}>
                  <View>
                    <Text style={styles.summaryText}>
                      Total No. Of Documents:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalNoOfDocuments}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>Total Amount Paid:</Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalAmountPaid}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Average Payment Monthly:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.averagePaymentMonthly}
                      </Text>
                    </View>
                  </View>
                </View>
              </>
            ) : type === "Purchase Document Listing" ? (
              <>
                <View style={{ flexDirection: "row", gap: 10 }}>
                  <View>
                    <Text style={styles.summaryText}>
                      Total No. Of Documents:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalNoOfDocuments}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Total Purchase Amount:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalPurchaseAmount}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>Total Tax:</Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalTaxAmount}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>Total Discount:</Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalDiscountAmount}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Total Amount After Tax:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalAmountAfterTax}
                      </Text>
                    </View>
                  </View>
                  <View>
                    <Text style={styles.summaryText}>
                      Total Amount After Discount:
                    </Text>
                    <View style={styles.summaryField}>
                      <Text style={styles.summaryTextValue}>
                        {purchaseReportData.totalAmountAfterDiscount}
                      </Text>
                    </View>
                  </View>
                </View>
              </>
            ) : (
              <>
                <Text style={styles.summaryText}>No Summary!</Text>
              </>
            )}
          </View>
        </View>

        {/* Footer */}
        <View fixed style={styles.footerContainer}>
          <View style={styles.footerLine} />
          <View
            style={{
              flexDirection: "row",
              justifyContent: "space-between",
              paddingTop: 5,
            }}
          >
            <Text style={styles.footerText}>
              Date Generated: {moment().format("DD-MM-YYYY")}
            </Text>
            <Text
              style={styles.footerText}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages}`
              }
            />
          </View>
        </View>
      </Page>
    </Document>
  );
};

export default PurchaseReport;
